//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeetingPlanner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meeting
    {
        public int ID { get; set; }
        public string About { get; set; }
        public string Promoter { get; set; }
        public string Treat { get; set; }
        public int Room_ID { get; set; }
        public System.DateTime BeginDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public int Confirmation_ID { get; set; }
        public string ParticipantInner { get; set; }
        public string ParticipantOuter { get; set; }
    
        public virtual Confirmation Confirmation { get; set; }
        public virtual Room Room { get; set; }
    }
}
