//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeetingPlanner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Participant
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public int Status_ID { get; set; }
    
        public virtual Status Status { get; set; }
    }
}
